version: '3'
services: 
  postgres:
    image: postgres
    container_name: postgres
    ports: 
      - '5432:5432'
    environment:
      # - TZ=Asia/Ho_Chi_Minh
      - POSTGRES_PASSWORD=ibEEAyq9a8VB6qRnPzzgVkeF3J7v0mtGdoyGGCMWjgPwPELEdN