import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../app/globals.scss'
import NextAuthProvider from '@/provider/NextauthProvider'
import ReduxProvider from '@/provider/ReduxProvider'
import RootClientLayout from '@/components/RootClientLayout';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Testcase Recommendation System - TRS</title>
        <meta name='description' content='TRS'/>
      </head>
      <body className={`${inter.className} bg-basic-3 h-screen`}>
        <RootClientLayout>
          <main>{children}</main>
        </RootClientLayout>
      </body>
    </html>
  )
}
